version: '3.8'

services:
  neutral-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - CLIENT_PORT=3001
    volumes:
      - ./config/environments/development.env:/app/.env
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - neutral-app-network

  # Optional: Add database service for development
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: neutral_app_dev
  #     POSTGRES_USER: dev_user
  #     POSTGRES_PASSWORD: dev_password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - neutral-app-network

networks:
  neutral-app-network:
    driver: bridge

# volumes:
#   postgres_data: 